#!/usr/bin/env bash
# Configure UFW to block all incoming traffic except SSH, HTTP, and HTTPS

ufw default deny incoming
ufw default allow outgoing
ufw allow 22/tcp
ufw allow 80/tcp
ufw allow 443/tcp
ufw enable
