#!/usr/bin/env bash

apt-get update -y
apt-get install haproxy -y

cat <<EOF > /etc/haproxy/haproxy.cfg
global
    log /dev/log    local0
    log /dev/log    local1 notice
    daemon

defaults
    log     global
    mode    http
    option  httplog
    option  dontlognull
    timeout connect 5000
    timeout client  50000
    timeout server  50000

frontend http_front
    bind *:80
    default_backend http_back

backend http_back
    balance roundrobin
    server web-01 44.212.14.181:80 check
    server web-02 13.220.152.75:80 check
EOF

sed -i 's/ENABLED=0/ENABLED=1/' /etc/default/haproxy
service haproxy restart
