#!/usr/bin/env bash
# Installs Nginx and configures a permanent redirection.

apt-get -y update
apt-get -y install nginx
sed -i '/server_name _;/a \    rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-available/default
service nginx restart
