#!/usr/bin/env bash
# Installs Nginx and configures a custom 404 error page.

apt-get -y update
apt-get -y install nginx
echo "Ceci n'est pas une page" > /var/www/html/404.html
sed -i '/server_name _;/a \    error_page 404 /404.html;' /etc/nginx/sites-available/default
service nginx restart
