#!/usr/bin/env bash

# Install nginx if not installed
apt-get update -y
apt-get install nginx -y

# Create custom 404 page
echo "Ceci n'est pas une page" > /var/www/html/404.html

# Configure nginx to use custom 404 page
sed -i 's|index index.html index.htm;|index index.html index.htm;\n\terror_page 404 /404.html;\n\tlocation = /404.html {\n\t\tinternal;\n\t}|' /etc/nginx/sites-available/default

# Restart nginx
service nginx restart

